server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-hystrix-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  # ${spring.cloud.client.ip-address}:${server.port} = 自动获取主机IP和PORT
    prefer-ip-address: true
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true # 开启 可以使用服务降级等hystrix的功能  当开起了此配置，ribbon的超时设置失效